"""user-listing:many-to-one

Revision ID: 239e00de57c6
Revises: 0979c88fad87
Create Date: 2026-05-28 13:50:26.391159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239e00de57c6'
down_revision = '0979c88fad87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('listings_lessor_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('listings_lessor_id_key'), ['lessor_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
