"""Add rentor and lessor profiles

Revision ID: baeca4e0763c
Revises: c483949b181a
Create Date: 2026-06-23 16:25:27.738588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baeca4e0763c'
down_revision = 'c483949b181a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessor_profile',
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=True),
    sa.Column('preferred_listing_categories', sa.JSON(), nullable=True),
    sa.Column('payout_phone', sa.String(length=20), nullable=True),
    sa.Column('payout_bank_name', sa.String(length=100), nullable=True),
    sa.Column('payout_account_number', sa.String(length=100), nullable=True),
    sa.Column('total_listings', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('rentor_profiles',
    sa.Column('preferred_location', sa.String(length=255), nullable=True),
    sa.Column('max_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('preferred_categories', sa.JSON(), nullable=True),
    sa.Column('rental_frequency', sa.String(length=50), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('trust_scorers', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentor_profiles')
    op.drop_table('lessor_profile')
    # ### end Alembic commands ###
