"""add status to lessor_profile

Revision ID: bd271901ea76
Revises: d730bd94fa4a
Create Date: 2026-06-23 17:04:13.790179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd271901ea76'
down_revision = 'd730bd94fa4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessor_profiles', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
