"""Add rentor and lessor profiles

Revision ID: d730bd94fa4a
Revises: baeca4e0763c
Create Date: 2026-06-23 16:33:52.796954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd730bd94fa4a'
down_revision = 'baeca4e0763c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessor_profiles',
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=True),
    sa.Column('preferred_listing_categories', sa.JSON(), nullable=True),
    sa.Column('payout_phone', sa.String(length=20), nullable=True),
    sa.Column('payout_bank_name', sa.String(length=100), nullable=True),
    sa.Column('payout_account_number', sa.String(length=100), nullable=True),
    sa.Column('total_listings', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('lessor_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessor_profile',
    sa.Column('display_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('business_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('preferred_listing_categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('payout_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payout_bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payout_account_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_listings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('lessor_profile_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lessor_profile_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('lessor_profile_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('uuid', name=op.f('lessor_profile_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('lessor_profiles')
    # ### end Alembic commands ###
