"""category-listing:many-to-one-fixed

Revision ID: f192749f8b44
Revises: 239e00de57c6
Create Date: 2026-05-28 13:53:57.377621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f192749f8b44'
down_revision = '239e00de57c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_categories',
    sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('listing_categories_category_id_fkey')),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('listing_categories_listing_id_fkey')),
    sa.PrimaryKeyConstraint('listing_id', 'category_id', name=op.f('listing_categories_pkey'))
    )
    # ### end Alembic commands ###
